--
-- PostgreSQL database dump
--

\restrict xjKd0ohiCKqOGjfduOiG6N5x9oOpaMDoFk5y7mULk9twi79CKrxeDaFomiee6EF

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AspNetRoleClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoleClaims" (
    "Id" integer NOT NULL,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetRoleClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetRoleClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text
);


--
-- Name: AspNetUserClaims; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserClaims" (
    "Id" integer NOT NULL,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text
);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."AspNetUserClaims" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AspNetUserClaims_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AspNetUserLogins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL
);


--
-- Name: AspNetUserRoles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL
);


--
-- Name: AspNetUserTokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text
);


--
-- Name: AspNetUsers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."AspNetUsers" (
    "Id" text NOT NULL,
    "DisplayName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL
);


--
-- Name: Categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Categories" (
    "Id" integer NOT NULL,
    "Name" character varying(64) NOT NULL,
    "Description" character varying(256)
);


--
-- Name: Categories_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Categories" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Categories_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ItemTags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ItemTags" (
    "ItemId" integer NOT NULL,
    "TagId" integer NOT NULL
);


--
-- Name: Items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Items" (
    "Id" integer NOT NULL,
    "Title" character varying(128) NOT NULL,
    "Description" character varying(2000) NOT NULL,
    "Price" numeric(18,2) NOT NULL,
    "ImageUrl" character varying(512),
    "CreatedAt" timestamp with time zone NOT NULL,
    "OwnerId" text NOT NULL,
    "CategoryId" integer NOT NULL
);


--
-- Name: Items_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Items" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Items_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Orders" (
    "Id" integer NOT NULL,
    "Quantity" integer NOT NULL,
    "Comment" character varying(500),
    "Status" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UserId" text NOT NULL,
    "ItemId" integer NOT NULL
);


--
-- Name: Orders_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Orders" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Orders_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Tags" (
    "Id" integer NOT NULL,
    "Name" character varying(32) NOT NULL
);


--
-- Name: Tags_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Tags" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Tags_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- Data for Name: AspNetRoleClaims; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetRoles; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUserClaims; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUserLogins; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUserRoles; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUserTokens; Type: TABLE DATA; Schema: public; Owner: -
--



--
-- Data for Name: AspNetUsers; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."AspNetUsers" VALUES ('bc1d45d8-83cd-4817-9213-c2e09f121db9', 'Алиса', '2026-05-27 01:57:20.44728+04', 'alice@example.com', 'ALICE@EXAMPLE.COM', 'alice@example.com', 'ALICE@EXAMPLE.COM', true, 'AQAAAAIAAYagAAAAENx8ABv28G2bdlwi2M+RA08iywNRi+TWUaqtvKr7pJVbm2vQASjJ5ib2dQnLLvwbYg==', 'KGNPZ3KMCXNFFNJCXYCGDYOCXDFOOWM3', '199cc662-f6ee-448d-8233-5f27e46bec70', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('4178263f-3dd9-458b-a4c5-f7f65fe8cbd8', 'Боб', '2026-05-27 01:57:20.638107+04', 'bob@example.com', 'BOB@EXAMPLE.COM', 'bob@example.com', 'BOB@EXAMPLE.COM', true, 'AQAAAAIAAYagAAAAEIEfIDY+VNrShYGN9fpbFdVGABSVNeVqVfZwYUo6+X3Oj2Pj1/At4hiMl8MWZLs2QA==', 'IY5YX32CJEPE6CZYE6QRI6OW23EPBGVD', '91358666-ccc8-4fb9-9e78-1d30fa2a5070', NULL, false, false, NULL, true, 0);
INSERT INTO public."AspNetUsers" VALUES ('46e5f9ef-96b6-40d8-bc62-77387e97d2bf', 'Кэрол', '2026-05-27 01:57:20.695841+04', 'carol@example.com', 'CAROL@EXAMPLE.COM', 'carol@example.com', 'CAROL@EXAMPLE.COM', true, 'AQAAAAIAAYagAAAAEAlhVOZ4u12oZYGPfwyP9xZFoVEPwo33Y8KSAih7zqICLiydZDy1bKsDoaN3nT5zAQ==', 'EXYVCSC65NTO7IE2F35GDC3QYJHR3EWE', 'fb42b2ea-7f71-4527-83f8-43356d5fcc94', NULL, false, false, NULL, true, 0);


--
-- Data for Name: Categories; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Categories" VALUES (1, 'Электроника', 'Универсальная категория «Электроника»');
INSERT INTO public."Categories" VALUES (2, 'Книги', 'Универсальная категория «Книги»');
INSERT INTO public."Categories" VALUES (3, 'Одежда', 'Универсальная категория «Одежда»');
INSERT INTO public."Categories" VALUES (4, 'Дом и сад', 'Универсальная категория «Дом и сад»');
INSERT INTO public."Categories" VALUES (5, 'Спорт', 'Универсальная категория «Спорт»');


--
-- Data for Name: ItemTags; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."ItemTags" VALUES (1, 1);
INSERT INTO public."ItemTags" VALUES (1, 2);
INSERT INTO public."ItemTags" VALUES (2, 2);
INSERT INTO public."ItemTags" VALUES (3, 3);
INSERT INTO public."ItemTags" VALUES (3, 5);
INSERT INTO public."ItemTags" VALUES (4, 3);
INSERT INTO public."ItemTags" VALUES (5, 4);
INSERT INTO public."ItemTags" VALUES (6, 4);
INSERT INTO public."ItemTags" VALUES (6, 5);
INSERT INTO public."ItemTags" VALUES (7, 2);
INSERT INTO public."ItemTags" VALUES (7, 6);
INSERT INTO public."ItemTags" VALUES (8, 6);


--
-- Data for Name: Items; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Items" VALUES (1, 'Беспроводные наушники', 'Удобные наушники с шумоподавлением, до 30 часов работы.', 5990.00, NULL, '2026-05-27 01:57:20.808479+04', 'bc1d45d8-83cd-4817-9213-c2e09f121db9', 1);
INSERT INTO public."Items" VALUES (2, 'Смарт-часы Pro', 'Спортивные часы с пульсометром и GPS.', 12990.00, NULL, '2026-05-26 01:57:20.808479+04', 'bc1d45d8-83cd-4817-9213-c2e09f121db9', 1);
INSERT INTO public."Items" VALUES (3, 'Книга «Чистый код»', 'Классика для разработчиков. Подержанная, но в отличном состоянии.', 950.00, NULL, '2026-05-25 01:57:20.808479+04', '4178263f-3dd9-458b-a4c5-f7f65fe8cbd8', 2);
INSERT INTO public."Items" VALUES (4, 'Зимняя куртка', 'Тёплая куртка размер L. Носилась один сезон.', 4500.00, NULL, '2026-05-24 01:57:20.808479+04', '4178263f-3dd9-458b-a4c5-f7f65fe8cbd8', 3);
INSERT INTO public."Items" VALUES (5, 'Набор садовых инструментов', 'Лопата, грабли, секатор — всё в одном комплекте.', 2100.00, NULL, '2026-05-23 01:57:20.808479+04', '46e5f9ef-96b6-40d8-bc62-77387e97d2bf', 4);
INSERT INTO public."Items" VALUES (6, 'Йога-мат премиум', 'Нескользящий коврик, толщина 6 мм, удобный ремень для переноски.', 1800.00, NULL, '2026-05-22 01:57:20.808479+04', '46e5f9ef-96b6-40d8-bc62-77387e97d2bf', 5);
INSERT INTO public."Items" VALUES (7, 'Кофемашина капсульная', 'Бесшумная, готовит за 30 секунд. В комплекте 20 капсул.', 7990.00, NULL, '2026-05-21 01:57:20.808479+04', 'bc1d45d8-83cd-4817-9213-c2e09f121db9', 1);
INSERT INTO public."Items" VALUES (8, 'Велосипед городской', 'Скоростной городской велосипед, 7 передач, размер M.', 18900.00, NULL, '2026-05-20 01:57:20.808479+04', '4178263f-3dd9-458b-a4c5-f7f65fe8cbd8', 5);


--
-- Data for Name: Orders; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Orders" VALUES (1, 1, 'Хочу попробовать', 0, '2026-05-26 01:57:20.808479+04', '4178263f-3dd9-458b-a4c5-f7f65fe8cbd8', 1);
INSERT INTO public."Orders" VALUES (2, 1, 'Заберу завтра', 1, '2026-05-24 01:57:20.808479+04', 'bc1d45d8-83cd-4817-9213-c2e09f121db9', 3);
INSERT INTO public."Orders" VALUES (3, 2, NULL, 3, '2026-05-22 01:57:20.808479+04', '4178263f-3dd9-458b-a4c5-f7f65fe8cbd8', 6);


--
-- Data for Name: Tags; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."Tags" VALUES (1, 'новое');
INSERT INTO public."Tags" VALUES (2, 'хит');
INSERT INTO public."Tags" VALUES (3, 'распродажа');
INSERT INTO public."Tags" VALUES (4, 'ручная работа');
INSERT INTO public."Tags" VALUES (5, 'эко');
INSERT INTO public."Tags" VALUES (6, 'ограниченная серия');


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public."__EFMigrationsHistory" VALUES ('20260526215606_Init', '8.0.11');


--
-- Name: AspNetRoleClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetRoleClaims_Id_seq"', 1, false);


--
-- Name: AspNetUserClaims_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."AspNetUserClaims_Id_seq"', 1, false);


--
-- Name: Categories_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Categories_Id_seq"', 5, true);


--
-- Name: Items_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Items_Id_seq"', 8, true);


--
-- Name: Orders_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Orders_Id_seq"', 3, true);


--
-- Name: Tags_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."Tags_Id_seq"', 6, true);


--
-- Name: AspNetRoleClaims PK_AspNetRoleClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetRoles PK_AspNetRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoles"
    ADD CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id");


--
-- Name: AspNetUserClaims PK_AspNetUserClaims; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id");


--
-- Name: AspNetUserLogins PK_AspNetUserLogins; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey");


--
-- Name: AspNetUserRoles PK_AspNetUserRoles; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId");


--
-- Name: AspNetUserTokens PK_AspNetUserTokens; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name");


--
-- Name: AspNetUsers PK_AspNetUsers; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUsers"
    ADD CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id");


--
-- Name: Categories PK_Categories; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Categories"
    ADD CONSTRAINT "PK_Categories" PRIMARY KEY ("Id");


--
-- Name: ItemTags PK_ItemTags; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemTags"
    ADD CONSTRAINT "PK_ItemTags" PRIMARY KEY ("ItemId", "TagId");


--
-- Name: Items PK_Items; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "PK_Items" PRIMARY KEY ("Id");


--
-- Name: Orders PK_Orders; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "PK_Orders" PRIMARY KEY ("Id");


--
-- Name: Tags PK_Tags; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Tags"
    ADD CONSTRAINT "PK_Tags" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: EmailIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "EmailIndex" ON public."AspNetUsers" USING btree ("NormalizedEmail");


--
-- Name: IX_AspNetRoleClaims_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON public."AspNetRoleClaims" USING btree ("RoleId");


--
-- Name: IX_AspNetUserClaims_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserClaims_UserId" ON public."AspNetUserClaims" USING btree ("UserId");


--
-- Name: IX_AspNetUserLogins_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserLogins_UserId" ON public."AspNetUserLogins" USING btree ("UserId");


--
-- Name: IX_AspNetUserRoles_RoleId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON public."AspNetUserRoles" USING btree ("RoleId");


--
-- Name: IX_Categories_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Categories_Name" ON public."Categories" USING btree ("Name");


--
-- Name: IX_ItemTags_TagId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ItemTags_TagId" ON public."ItemTags" USING btree ("TagId");


--
-- Name: IX_Items_CategoryId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_CategoryId" ON public."Items" USING btree ("CategoryId");


--
-- Name: IX_Items_OwnerId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_OwnerId" ON public."Items" USING btree ("OwnerId");


--
-- Name: IX_Items_Title; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Items_Title" ON public."Items" USING btree ("Title");


--
-- Name: IX_Orders_ItemId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_ItemId" ON public."Orders" USING btree ("ItemId");


--
-- Name: IX_Orders_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_Orders_UserId" ON public."Orders" USING btree ("UserId");


--
-- Name: IX_Tags_Name; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_Tags_Name" ON public."Tags" USING btree ("Name");


--
-- Name: RoleNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "RoleNameIndex" ON public."AspNetRoles" USING btree ("NormalizedName");


--
-- Name: UserNameIndex; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "UserNameIndex" ON public."AspNetUsers" USING btree ("NormalizedUserName");


--
-- Name: AspNetRoleClaims FK_AspNetRoleClaims_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetRoleClaims"
    ADD CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserClaims FK_AspNetUserClaims_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserClaims"
    ADD CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserLogins FK_AspNetUserLogins_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserLogins"
    ADD CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetRoles_RoleId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES public."AspNetRoles"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserRoles FK_AspNetUserRoles_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserRoles"
    ADD CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: AspNetUserTokens FK_AspNetUserTokens_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."AspNetUserTokens"
    ADD CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE CASCADE;


--
-- Name: ItemTags FK_ItemTags_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemTags"
    ADD CONSTRAINT "FK_ItemTags_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE CASCADE;


--
-- Name: ItemTags FK_ItemTags_Tags_TagId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ItemTags"
    ADD CONSTRAINT "FK_ItemTags_Tags_TagId" FOREIGN KEY ("TagId") REFERENCES public."Tags"("Id") ON DELETE CASCADE;


--
-- Name: Items FK_Items_AspNetUsers_OwnerId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_AspNetUsers_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Items FK_Items_Categories_CategoryId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Items"
    ADD CONSTRAINT "FK_Items_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES public."Categories"("Id") ON DELETE RESTRICT;


--
-- Name: Orders FK_Orders_AspNetUsers_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES public."AspNetUsers"("Id") ON DELETE RESTRICT;


--
-- Name: Orders FK_Orders_Items_ItemId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Orders"
    ADD CONSTRAINT "FK_Orders_Items_ItemId" FOREIGN KEY ("ItemId") REFERENCES public."Items"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict xjKd0ohiCKqOGjfduOiG6N5x9oOpaMDoFk5y7mULk9twi79CKrxeDaFomiee6EF

